spring:
  application:
    name: notetaker-service
    
server:
  port: 8080

---
# Actuator
management:
  port: 8081

---
# HTTP encoding
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
spring:
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8

logging:
  file: notetaker-services.log
  level: com.aver=DEBUG
  path: /Users/mathew/temp
    
---
endpoints:
  logfile:
    enabled: true
    path: /logfile
    sensitive: false
  metrics:
    enabled: true
  info:
    enabled: true
  

--- 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
